import { IColor } from '../types/IColor';

export const allColors: IColor[] = [
  {
    color: '#1c012e',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh11',
    isMostCommon: true,
  },
  {
    color: '#6d00ad',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh12',
    isMostCommon: true,
  },
  {
    color: '#f8f8f8',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh13',
    isMostCommon: false,
  },
  {
    color: '#681DB8',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh14',
    isMostCommon: true,
  },
  {
    color: '#fff',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh15',
    isMostCommon: false,
  },
  {
    color: '#6a56c3',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh16',
    isMostCommon: true,
  },
  {
    color: '#79a1d7',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh17',
    isMostCommon: false,
  },
  {
    color: '#81badd',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh18',
    isMostCommon: false,
  },
  {
    color: '#8cc8dc',
    isFavorite: true,
    type: 'solid',
    id: 'dlkamfklnmsdfgh19',
    isMostCommon: false,
  },
  {
    color: '#a3eadd',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh20',
    isMostCommon: false,
  },
  {
    color: '#b0fbde',
    isFavorite: false,
    type: 'solid',
    id: 'dlkamfklnmsdfgh21',
    isMostCommon: false,
  },
  {
    color: 'linear-gradient(to right, #904e95, #e96443);',
    isFavorite: true,
    type: 'gradient',
    id: 'dlkamfklnmsdfgh22',
    isMostCommon: false,
  },
  {
    color: 'linear-gradient(to right, #FFC371, #FF5F6D);',
    isFavorite: false,
    type: 'gradient',
    id: 'dlkamfklnmsdfgh23',
    isMostCommon: true,
  },
];
